# Generated by Django 3.2.9 on 2022-07-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='canal',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='phone',
            field=models.CharField(default='airtel-money', max_length=255),
            preserve_default=False,
        ),
    ]
