# Generated by Django 3.2.9 on 2022-07-05 10:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_alter_category_cover'),
        ('tickets', '0011_alter_purchase_unique_together'),
        ('payments', '0002_auto_20220705_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('user', 'event', 'ticket')},
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
    ]
