# Generated by Django 3.2.9 on 2022-07-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20220705_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='canal',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
