# Generated by Django 3.2.9 on 2022-04-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220410_2222'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='email déjà utilisé',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('email',), name='Email déjà utilisé'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('phone_number',), name='Numéro de téléphone déjà utilisé'),
        ),
    ]
