# Generated by Django 3.2.9 on 2022-06-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='long',
            field=models.FloatField(null=True),
        ),
    ]
