# Generated by Django 3.2.9 on 2022-07-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_fcm_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fcm_token',
            new_name='notif_token',
        ),
    ]
