# Generated by Django 3.2.9 on 2022-09-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_fcm_token_user_notif_token'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='Numéro de téléphone déjà utilisé',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
