# Generated by Django 3.2.9 on 2021-11-10 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('ticket', 'user', 'interval')},
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='availability',
        ),
    ]
