# Generated by Django 3.2.9 on 2021-11-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20211110_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
