# Generated by Django 3.2.9 on 2021-11-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_purchase_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='interval',
            field=models.FloatField(default=0),
        ),
    ]
