# Generated by Django 3.2.9 on 2022-03-06 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0006_alter_purchase_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='caption',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='number_of_place',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='currency',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('cover', models.CharField(max_length=255)),
                ('event_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='tickets.event'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('event', 'name')},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='place',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
