# Generated by Django 3.2.9 on 2022-07-05 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_canal'),
        ('tickets', '0011_alter_purchase_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment'),
        ),
    ]
