# Generated by Django 3.2.9 on 2022-04-19 12:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_alter_category_cover'),
        ('agents', '0002_auto_20220325_0838'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agent',
            unique_together={('user', 'event')},
        ),
    ]
